# Generated by Django 4.2.9 on 2024-07-27 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonVi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Ngày cập nhật"
                    ),
                ),
                (
                    "ten_don_vi",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tên đơn vị"
                    ),
                ),
                ("ma", models.CharField(max_length=50, unique=True, verbose_name="Mã")),
                ("mo_ta", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "trang_thai",
                    models.BooleanField(default=True, verbose_name="Trạng thái"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, to="auth.group", verbose_name="Nhóm quyền"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="home.donvi",
                        verbose_name="Đơn vị cha",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "03. Đơn Vị",
                "db_table": "DonVi",
            },
        ),
        migrations.CreateModel(
            name="GiaLuuTru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Ngày cập nhật"
                    ),
                ),
                ("gia_so", models.CharField(max_length=50, verbose_name="Giá số")),
                ("ten", models.CharField(max_length=255, verbose_name="Tên giá")),
                ("mo_ta", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "sap_xep",
                    models.PositiveIntegerField(default=0, verbose_name="Sắp xếp"),
                ),
                (
                    "trang_thai",
                    models.BooleanField(default=True, verbose_name="Trạng thái"),
                ),
            ],
            options={
                "verbose_name_plural": "02. Giá Lưu Trữ",
                "db_table": "GiaLuuTru",
            },
        ),
        migrations.CreateModel(
            name="HopLuuTru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Ngày cập nhật"
                    ),
                ),
                ("hop_so", models.CharField(max_length=50, verbose_name="Hộp số")),
                ("mo_ta", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "tu_nam",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Từ năm"
                    ),
                ),
                (
                    "den_nam",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Đến năm"
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        default="Còn trống", max_length=50, verbose_name="Trạng thái"
                    ),
                ),
                (
                    "gia_luu_tru",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.gialuutru",
                        verbose_name="Giá lưu trữ",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "06. Hộp Lưu Trữ",
                "db_table": "HopLuuTru",
            },
        ),
        migrations.CreateModel(
            name="HoSo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Ngày cập nhật"
                    ),
                ),
                ("tieu_de", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("ho_so_so", models.CharField(max_length=50, verbose_name="Hồ sơ số")),
                (
                    "ma_ho_so",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Mã hồ sơ"
                    ),
                ),
                (
                    "che_do_su_dung",
                    models.CharField(max_length=255, verbose_name="Chế độ sử dụng"),
                ),
                ("ngon_ngu", models.CharField(max_length=100, verbose_name="Ngôn ngữ")),
                (
                    "tong_so_van_ban_trong_ho_so",
                    models.IntegerField(
                        default=0, verbose_name="Tổng số văn bản trong hồ sơ"
                    ),
                ),
                (
                    "thoi_gian_bat_dau",
                    models.DateField(verbose_name="Thời gian bắt đầu"),
                ),
                (
                    "thoi_gian_ket_thuc",
                    models.DateField(
                        blank=True, null=True, verbose_name="Thời gian kết thúc"
                    ),
                ),
                ("chu_giai", models.TextField(blank=True, verbose_name="Chú giải")),
                (
                    "ky_hieu_thong_tin",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ký hiệu thông tin"
                    ),
                ),
                (
                    "tu_khoa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Từ khóa"
                    ),
                ),
                (
                    "so_luong_to",
                    models.IntegerField(default=0, verbose_name="Số lượng tờ"),
                ),
                (
                    "so_luong_trang",
                    models.IntegerField(default=0, verbose_name="Số lượng trang"),
                ),
                (
                    "tinh_trang_vat_ly",
                    models.TextField(blank=True, verbose_name="Tình trạng vật lý"),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("da_so_hoa", "Đã số hóa"),
                            ("chua_so_hoa", "Chưa số hóa"),
                        ],
                        default="chua_so_hoa",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "hop_luu_tru",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.hopluutru",
                        verbose_name="Hộp lưu trữ",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "02. Hồ Sơ",
                "db_table": "HoSo",
            },
        ),
        migrations.CreateModel(
            name="KhoLuuTru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Ngày cập nhật"
                    ),
                ),
                (
                    "ten_kho",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tên kho"
                    ),
                ),
                ("mo_ta", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "sap_xep",
                    models.PositiveIntegerField(default=0, verbose_name="Sắp xếp"),
                ),
                (
                    "trang_thai",
                    models.BooleanField(default=True, verbose_name="Trạng thái"),
                ),
            ],
            options={
                "verbose_name_plural": "01. Kho Lưu Trữ",
                "db_table": "KhoLuuTru",
            },
        ),
        migrations.CreateModel(
            name="LoaiVanBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Ngày cập nhật"
                    ),
                ),
                (
                    "ten",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tên loại văn bản"
                    ),
                ),
                (
                    "ten_viet_tat",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tên viết tắt"
                    ),
                ),
                (
                    "sap_xep",
                    models.PositiveIntegerField(default=0, verbose_name="Sắp xếp"),
                ),
                (
                    "trang_thai",
                    models.BooleanField(default=True, verbose_name="Trạng thái"),
                ),
            ],
            options={
                "verbose_name_plural": "08. Loại Văn Bản",
                "db_table": "LoaiVanBan",
            },
        ),
        migrations.CreateModel(
            name="PhanLoaiTaiLieuLuuTru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Ngày cập nhật"
                    ),
                ),
                (
                    "ten",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tên phân loại"
                    ),
                ),
                ("mo_ta", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "sap_xep",
                    models.PositiveIntegerField(default=0, verbose_name="Sắp xếp"),
                ),
                (
                    "trang_thai",
                    models.BooleanField(default=True, verbose_name="Trạng thái"),
                ),
            ],
            options={
                "verbose_name_plural": "09. Phân Loại Tài Liệu Lưu Trữ",
                "db_table": "PhanLoaiTaiLieuLuuTru",
            },
        ),
        migrations.CreateModel(
            name="ThoiHanLuuTru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Ngày cập nhật"
                    ),
                ),
                (
                    "ten",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tên thời hạn"
                    ),
                ),
                ("so_nam", models.PositiveIntegerField(verbose_name="Số năm")),
                (
                    "sap_xep",
                    models.PositiveIntegerField(default=0, verbose_name="Sắp xếp"),
                ),
                (
                    "trang_thai",
                    models.BooleanField(default=True, verbose_name="Trạng thái"),
                ),
            ],
            options={
                "verbose_name_plural": "07. Thời Hạn Lưu Trữ",
                "db_table": "ThoiHanLuuTru",
            },
        ),
        migrations.CreateModel(
            name="VanBan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Ngày cập nhật"
                    ),
                ),
                (
                    "so_thu_tu_van_ban_trong_ho_so",
                    models.IntegerField(verbose_name="Số thứ tự văn bản trong hồ sơ"),
                ),
                (
                    "ma_dinh_danh_van_ban",
                    models.CharField(
                        max_length=50, verbose_name="Mã định danh văn bản"
                    ),
                ),
                (
                    "so_van_ban",
                    models.CharField(max_length=50, verbose_name="Số văn bản"),
                ),
                (
                    "ky_hieu_cua_van_ban",
                    models.CharField(max_length=50, verbose_name="Ký hiệu của văn bản"),
                ),
                ("ngay_ban_hanh", models.DateField(verbose_name="Ngày ban hành")),
                (
                    "co_quan_to_chuc_ban_hanh",
                    models.CharField(
                        max_length=255, verbose_name="Cơ quan/Tổ chức ban hành"
                    ),
                ),
                (
                    "trich_yeu_noi_dung",
                    models.TextField(verbose_name="Trích yếu nội dung"),
                ),
                (
                    "tu_so",
                    models.IntegerField(blank=True, null=True, verbose_name="Từ số"),
                ),
                (
                    "den_so",
                    models.IntegerField(blank=True, null=True, verbose_name="Đến số"),
                ),
                ("ngon_ngu", models.CharField(max_length=100, verbose_name="Ngôn ngữ")),
                ("so_luong_trang", models.IntegerField(verbose_name="Số lượng trang")),
                (
                    "ky_hieu_thong_tin",
                    models.CharField(max_length=100, verbose_name="Ký hiệu thông tin"),
                ),
                ("tu_khoa", models.CharField(max_length=255, verbose_name="Từ khóa")),
                (
                    "che_do_su_dung",
                    models.CharField(max_length=100, verbose_name="Chế độ sử dụng"),
                ),
                (
                    "muc_do_tin_cay",
                    models.CharField(max_length=100, verbose_name="Mức độ tin cậy"),
                ),
                ("but_tich", models.CharField(max_length=255, verbose_name="Bút tích")),
                (
                    "tinh_trang_vat_ly",
                    models.CharField(max_length=255, verbose_name="Tình trạng vật lý"),
                ),
                ("ghi_chu", models.TextField(verbose_name="Ghi chú")),
                (
                    "ho_so",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.hoso",
                        verbose_name="Hồ sơ",
                    ),
                ),
                (
                    "loai_van_ban",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.loaivanban",
                        verbose_name="Loại văn bản",
                    ),
                ),
                (
                    "thoi_han_bao_quan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.thoihanluutru",
                        verbose_name="Thời hạn bảo quản",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "03. Văn Bản",
                "db_table": "VanBan",
            },
        ),
        migrations.CreateModel(
            name="TapTinDinhKem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tep_tin",
                    models.FileField(
                        upload_to="uploads/vanban/%Y/%m/%d/", verbose_name="Tệp tin"
                    ),
                ),
                (
                    "van_ban",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tep_dinh_kem",
                        to="home.vanban",
                        verbose_name="Văn bản",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "03. Tệp đính kèm",
                "db_table": "TapTinDinhKem",
            },
        ),
        migrations.CreateModel(
            name="PhongLuuTru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Ngày cập nhật"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1024, verbose_name="Tên phông lưu trữ"),
                ),
                ("phong_so", models.IntegerField(verbose_name="Phông số")),
                (
                    "lich_su_don_vi_hinh_thanh_phong",
                    models.TextField(
                        blank=True, verbose_name="Lịch sử đơn vị hình thành phòng"
                    ),
                ),
                ("nam_bat_dau", models.IntegerField(verbose_name="Năm bắt đầu")),
                (
                    "nam_ket_thuc",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Năm kết thúc"
                    ),
                ),
                (
                    "tong_so_tai_lieu_giay",
                    models.IntegerField(
                        default=0, verbose_name="Tổng số tài liệu giấy"
                    ),
                ),
                (
                    "so_luong_tai_lieu_giay_da_so_hoa",
                    models.IntegerField(
                        default=0, verbose_name="Số lượng tài liệu giấy đã số hóa"
                    ),
                ),
                (
                    "so_luong_trang_tai_lieu_da_lap_ban_sao_bao_hiem",
                    models.IntegerField(
                        default=0,
                        verbose_name="Số lượng trang tài liệu đã lập bản sao bảo hiểm",
                    ),
                ),
                (
                    "cac_nhom_tai_lieu_chu_yeu",
                    models.TextField(
                        blank=True, verbose_name="Các nhóm tài liệu chủ yếu"
                    ),
                ),
                (
                    "cac_loai_hinh_tai_lieu_khac",
                    models.TextField(
                        blank=True, verbose_name="Các loại hình tài liệu khác"
                    ),
                ),
                (
                    "ngon_ngu",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ngôn ngữ"
                    ),
                ),
                (
                    "cong_cu_tra_cuu",
                    models.TextField(blank=True, verbose_name="Công cụ tra cứu"),
                ),
                ("ghi_chu", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("da_so_hoa", "Đã số hóa"),
                            ("chua_so_hoa", "Chưa số hóa"),
                        ],
                        default="chua_so_hoa",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "don_vi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.donvi",
                        verbose_name="Đơn vị",
                    ),
                ),
                (
                    "kho_luu_tru",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.kholuutru",
                        verbose_name="Kho lưu trữ",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "01. Phông lưu trữ",
                "db_table": "PhongLuuTru",
            },
        ),
        migrations.CreateModel(
            name="MucLucHoSo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Ngày cập nhật"
                    ),
                ),
                (
                    "muc_luc_so",
                    models.CharField(max_length=50, verbose_name="Mục lục số"),
                ),
                (
                    "so_trang",
                    models.PositiveIntegerField(default=0, verbose_name="Số trang"),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        default="Đang cập nhật",
                        max_length=50,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "phong_luu_tru",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.phongluutru",
                        verbose_name="Phông lưu trữ",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "05. Mục Lục Hồ Sơ",
                "db_table": "MucLucHoSo",
            },
        ),
        migrations.AddField(
            model_name="hoso",
            name="muc_luc_ho_so",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.mucluchoso",
                verbose_name="Mục lục hồ sơ",
            ),
        ),
        migrations.AddField(
            model_name="hoso",
            name="phan_loai_tai_lieu_luu_tru",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.phanloaitailieuluutru",
                verbose_name="Loại tài liệu lưu trữ",
            ),
        ),
        migrations.AddField(
            model_name="hoso",
            name="phong_luu_tru",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.phongluutru",
                verbose_name="Phòng lưu trữ",
            ),
        ),
        migrations.AddField(
            model_name="hoso",
            name="thoi_han_bao_quan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.thoihanluutru",
                verbose_name="Thời hạn bảo quản",
            ),
        ),
        migrations.AddField(
            model_name="hopluutru",
            name="kho_luu_tru",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.kholuutru",
                verbose_name="Kho lưu trữ",
            ),
        ),
        migrations.AddField(
            model_name="hopluutru",
            name="muc_luc_ho_so",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.mucluchoso",
                verbose_name="Mục lục hồ sơ",
            ),
        ),
        migrations.AddField(
            model_name="hopluutru",
            name="phong_luu_tru",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.phongluutru",
                verbose_name="Phông lưu trữ",
            ),
        ),
        migrations.AddField(
            model_name="gialuutru",
            name="kho_luu_tru",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.kholuutru",
                verbose_name="Kho lưu trữ",
            ),
        ),
        migrations.CreateModel(
            name="UserDonVi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="Là admin?"),
                ),
                (
                    "don_vi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.donvi",
                        verbose_name="Đơn vị",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "02. Quyền truy cập đơn vị",
                "db_table": "UserDonVi",
                "unique_together": {("user", "don_vi")},
            },
        ),
    ]
