# Generated by Django 4.2.9 on 2024-08-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vanban",
            name="trang_thai",
            field=models.CharField(
                choices=[("da_so_hoa", "Đã số hóa"), ("chua_so_hoa", "Chưa số hóa")],
                default="chua_so_hoa",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
